import Head from 'next/head'
import styles from '../styles/Layout.module.css'

export default function Layout({children}) {
    return(
        <div>
            <Head>
                <title>News App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.container}>
            <h3 className={styles.logo}>NewsApp</h3>
            { children }
            </div>
        </div>
    )
}